export interface SpiritsModel {
  _id: string,
  nev: string,
  csoport: string,
  kepessegek: string,
  fizEro: number,
  fizGyo: number,
  fizUgy: number,
  fizKit: number,
  asztEro: number,
  asztGyo: number,
  asztUgy: number,
  asztKit: number,
  szint: number,
  tamadas: string,
  szolgalatok: number,
  ar: number,
  karma: number,
  megjegyzes: string
};
