export const detailsUtil: Array<any> = [
  {meret: 70, fejlec: 'Teljes név', fcName:'teljesnev', tipus: 'text', megjegyzes: 'Amit a Sírodra vésnek...'},
  {meret: 30, fejlec: 'Életkor', fcName:'eletkor', tipus: 'number', unit: ' év'},
  {meret: 70, fejlec: 'Becenév', fcName:'becenev', tipus: 'text', megjegyzes: 'Ahogy a Haverok ismernek...'},
  {meret: 30, fejlec: 'Magasság', fcName:'magassag', tipus: 'number', unit: ' cm'},
  {meret: 70, fejlec: 'Álnév', fcName:'alnev', tipus: 'text', megjegyzes: 'Az Alvilágban így hívnak...'},
  {meret: 30, fejlec: 'Testsúly', fcName:'testsuly', tipus: 'number', unit: ' kg'},
  {meret: 30, fejlec: 'Anyanyelv', fcName:'anyanyelv', tipus: 'inpselect', listname:'Nyelvek', megjegyzes:'Ha kitolod, levágjuk...'},
  {meret: 30, fejlec: 'Faj', fcName:'fajta', tipus: 'select', listname:'Fajok', megjegyzes:'Fajta, te paraszt!'},
  {meret: 30, fejlec: 'Testalkat', fcName:'testalkat', tipus: 'text', megjegyzes: 'Mackós, vagy girhes?'},
  {meret: 30, fejlec: 'Nem', fcName:'nem', tipus: 'select', listname:'Nem', megjegyzes:'De! Vagy mit tudom én!?'},
  {meret: 30, fejlec: 'Szemszín', fcName:'szemszin', tipus: 'color'},
  {meret: 30, fejlec: 'Bőrszín', fcName:'borszin', tipus: 'color'},
  {meret: 30, fejlec: 'Hajszín', fcName:'hajszin', tipus: 'color'},
  {meret: 30, fejlec: 'Hajstílus', fcName:'hajstilus', tipus: 'text', megjegyzes: 'Az Árnyak között is fontos!'},
  {meret: 30, fejlec: 'Szőrzet színe', fcName:'szorszin', tipus: 'color'},
  {meret: 50, fejlec: 'Félelem', fcName:'felelem', tipus: 'text', megjegyzes: 'Mindenki fél valamitől...'},
  {meret: 50, fejlec: 'Ösztönző', fcName:'osztonzo', tipus: 'text', megjegyzes: 'De van, ami képes bátorítani!'},
  {meret: 50, fejlec: 'Gyűlölet', fcName:'gyulolet', tipus: 'text', megjegyzes: 'Ne a gyűlölet vezéreljen...'},
  {meret: 50, fejlec: 'Kedvenc', fcName:'kedvenc', tipus: 'text', megjegyzes: 'Hanem ami boldoggá tesz!'},
  {meret: 50, fejlec: 'Írtózat', fcName:'irtozat', tipus: 'text', megjegyzes: 'Lehet, mástól kifordul a beled...'},
  {meret: 50, fejlec: 'Vonzalom', fcName:'vonzalom', tipus: 'text', megjegyzes: 'De ennek te sem tudsz ellenállni!'},
  {meret: 100, fejlec: 'Egyéb jellemzők', fcName:'szakall', tipus: 'text', megjegyzes: 'Szakáll, smink, tetkó, meg ami a többi helyre nem fér el :)'},
  {meret: 100, fejlec: 'Különleges képességek', fcName:'kepessegek', tipus: 'kepessegek'},
];

export const Fajok: Array<any> = [
  {
    fajnev: 'Ember',
    karKockatartalekMin: 3,
    karKockatartalekMax: 3,
    defHeight: 180,
    defWieght: 75,
    defAge: 65,
    defKepessegek: [{kepesseg: '+3 Karmatartalék'}],
  },
  {
    fajnev: 'Tünde',
    karFizGyoMax: 1,
    karAsztAllMax: 2,
    defHeight: 180,
    defWieght: 70,
    defAge: 100,
    defKepessegek: [
      {kepesseg: 'Éjszakai látás'},
      {kepesseg: '1,2x jobb látás'},
      {kepesseg: '1,2x jobb hallás'},
    ],
  },
  {
    fajnev: 'Törpe',
    karFizEroMax: 2,
    karFizAll: 1,
    karAsztEroMax: 1,
    defHeight: 140,
    defWieght: 60,
    defAge: 100,
    defKepessegek: [
      {kepesseg: 'Hőlátás'},
      {kepesseg: 'Irányérzék'}
    ],
  },
  {
    fajnev: 'Ork',
    karFizEroMax: 2,
    karFizAllMax: 3,
    karAsztAllMax: -1,
    karAsztUgyMax: -1,
    defHeight: 190,
    defWieght: 95,
    defAge: 40,
    defKepessegek: [
      {kepesseg: 'Éjszakai látás'},
      {kepesseg: '1,2x jobb látás'},
      {kepesseg: '1,2x jobb hallás'},
    ],
  },
  {
    fajnev: 'Troll',
    karFizEroMax: 4,
    karFizGyoMax: -1,
    karFizAllMax: 4,
    karAsztAllMax: -2,
    karAsztUgyMax: -2,
    defHeight: 280,
    defWieght: 220,
    defAge: 50,
    defKepessegek: [
      {kepesseg: 'Hőlátás'},
      {kepesseg: '+1 Elérés'},
      {kepesseg: '+1 Test sebesülés ellen'},
    ],
  },
];

export const Nemek: Array<any> = [
  'Férfi',
  'Nő',
  'Mindkettő',
  'Egyiksem',
  'Egyéb',
];

export const Nyelvek: Array<any> = [
  'magyar',
  'angol',
  'francia',
  'orosz',
  'japán',
  'kínai',
  'indiai',
];

export const Hagyomanyok: Array<any> = [
  {text: 'Inaktív'},
  {text: 'Hermetikus'},
  {text: 'Fizikai Adeptus'},
  {text: 'Misztikus Adeptus'},
  {text: 'Aligátor Sámán'},
  {text: 'Bagoly Sámán'},
  {text: 'Medve Sámán'},
  {text: 'Bölény Sámán'},
  {text: 'Cápa Sámán'},
  {text: 'Delfin Sámán'},
  {text: 'Egér Sámán'},
  {text: 'Farkas Sámán'},
  {text: 'Holló Sámán'},
  {text: 'Kígyó Sámán'},
  {text: 'Kutya Sámán'},
  {text: 'Macska Sámán'},
  {text: 'Mosómedve Sámán'},
  {text: 'Oroszlán Sámán'},
  {text: 'Patkány Sámán'},
  {text: 'Prérifarkas Sámán'},
  {text: 'Sas Sámán'},
];
