export const detailsUtil: Array<any> = [
  {meret: 33, fejlec: 'Gének', fcName:'genek', tipus: 'select', megjegyzes:'Nem faj! Legfeljebb fajta te rasszista paraszt!'},
  {meret: 33, fejlec: 'Nem', fcName:'nem', tipus: 'select', megjegyzes:'Nem? De! Vagy mit tudom én!?'},
  {meret: 33, fejlec: 'Anyanyelv', fcName:'anyanyelv', tipus: 'inpselect', megjegyzes:'Kezdj el csicseregni, de ha kitolod, levágjuk...'},
  {meret: 66, fejlec: 'Teljes név', fcName:'teljesnev', tipus: 'text', megjegyzes: 'Amit a sírodra vésnek, ha kisimultak az intenzív vonalaid...'},
  {meret: 33, fejlec: 'Életkor', fcName:'eletkor', tipus: 'number', megjegyzes: 'Vajon ezért a vénségért mennyit kapni a rabszolgapiacon?', egyseg: ' év', lepes: 10},
  {meret: 66, fejlec: 'Becenév', fcName:'becenev', tipus: 'text', megjegyzes: 'Ahogy a haverok ismernek, már ha még élnek...'},
  {meret: 33, fejlec: 'Magasság', fcName:'magassag', tipus: 'number', megjegyzes: 'Ettől függ, hogy hokedlinek, vagy toronynak becéznek', egyseg: ' cm', lepes: 10},
  {meret: 66, fejlec: 'Álnév', fcName:'alnev', tipus: 'text', megjegyzes: 'Az alvilágban jobb, ha csak ezt ismerik...'},
  {meret: 33, fejlec: 'Testsúly', fcName:'testsuly', tipus: 'number', megjegyzes: 'Vajon lecsontozva mennyit ér a húsod?', egyseg: ' kg', lepes: 10},
  {meret: 33, fejlec: 'Testalkat', fcName:'testalkat', tipus: 'text', megjegyzes: 'Ki a mellet, be a hasat, hadd mártom meg benned a vasat!'},
  {meret: 33, fejlec: 'Szemszín', fcName:'szemszin', tipus: 'color', megjegyzes: 'Mi a kedvenc színed? Barna? Nem, a kékááá...'},
  {meret: 33, fejlec: 'Bőrszín', fcName:'borszin', tipus: 'color', megjegyzes: 'Hidd el, lassan már senkit nem érdekel, kivéve ha ember vagy.'},
  {meret: 33, fejlec: 'Hajszín', fcName:'hajszin', tipus: 'color', megjegyzes: 'Milyet szeretnél? Van egyáltalán saját hajad?'},
  {meret: 33, fejlec: 'Hajstílus', fcName:'hajstilus', tipus: 'text', megjegyzes: 'Az Árnyak között is fontos a jó megjelenés!'},
  {meret: 33, fejlec: 'Szőrzet színe', fcName:'szorszin', tipus: 'color', megjegyzes: 'A hajat szokták festeni, de milyen színű a fa... famentes papír?'},
  {meret: 50, fejlec: 'Félelem', fcName:'felelem', tipus: 'text', megjegyzes: 'Mindenki fél valamitől...'},
  {meret: 50, fejlec: 'Ösztönző', fcName:'osztonzo', tipus: 'text', megjegyzes: 'De van, ami képes bátorítani!'},
  {meret: 50, fejlec: 'Gyűlölet', fcName:'gyulolet', tipus: 'text', megjegyzes: 'Ne a gyűlölet vezéreljen...'},
  {meret: 50, fejlec: 'Kedvenc', fcName:'kedvenc', tipus: 'text', megjegyzes: 'Hanem az, ami boldoggá tesz!'},
  {meret: 50, fejlec: 'Írtózat', fcName:'irtozat', tipus: 'text', megjegyzes: 'Lehet, hogy valamitől kifordul a beled...'},
  {meret: 50, fejlec: 'Vonzalom', fcName:'vonzalom', tipus: 'text', megjegyzes: 'De ennek te sem tudsz ellenállni!'},
  {meret: 100, fejlec: 'Egyéb jellemzők, megjelenés', fcName:'megjelenes', tipus: 'text', megjegyzes: 'Szakáll, smink, tetkó, meg ami a többi helyre nem fér el :)'},
  {meret: 100, fejlec: 'Különleges képességek', fcName:'kepessegek', tipus: 'kepessegek'},
];

export const genekUtil: Array<any> = [
  {
    dns: 'Ember',
    karKockatartalekMin: 3,
    karKockatartalekMax: 3,
    defHeight: 175,
    defWieght: 85,
    defAge: 65,
    defKepessegek: [{kepesseg: '+3 Karmatartalék'}],
  },
  {
    dns: 'Tünde',
    karFizGyoMax: 1,
    karAsztAllMax: 2,
    defHeight: 180,
    defWieght: 70,
    defAge: 100,
    defKepessegek: [
      {kepesseg: 'Éjszakai látás'},
      {kepesseg: '1,2x jobb látás'},
      {kepesseg: '1,2x jobb hallás'},
    ],
  },
  {
    dns: 'Törpe',
    karFizEroMax: 2,
    karFizAll: 1,
    karAsztEroMax: 1,
    defHeight: 140,
    defWieght: 60,
    defAge: 100,
    defKepessegek: [
      {kepesseg: 'Hőlátás'},
      {kepesseg: 'Irányérzék'}
    ],
  },
  {
    dns: 'Ork',
    karFizEroMax: 2,
    karFizAllMax: 3,
    karAsztAllMax: -1,
    karAsztUgyMax: -1,
    defHeight: 190,
    defWieght: 95,
    defAge: 40,
    defKepessegek: [
      {kepesseg: 'Éjszakai látás'},
      {kepesseg: '1,2x jobb látás'},
      {kepesseg: '1,2x jobb hallás'},
    ],
  },
  {
    dns: 'Troll',
    karFizEroMax: 4,
    karFizGyoMax: -1,
    karFizAllMax: 4,
    karAsztAllMax: -2,
    karAsztUgyMax: -2,
    defHeight: 280,
    defWieght: 220,
    defAge: 50,
    defKepessegek: [
      {kepesseg: 'Hőlátás'},
      {kepesseg: '+1 Elérés'},
      {kepesseg: '+1 Test sebesülés ellen'},
    ],
  },
];

export const nemekUtil: Array<any> = [
  'Férfi',
  'Nő',
  'Mindkettő',
  'Egyiksem',
  'Egyéb',
];

export const nyelvekUtil: Array<any> = [
  'magyar',
  'angol',
  'francia',
  'orosz',
  'japán',
  'kínai',
  'indiai',
];

export const Hagyomanyok: Array<any> = [
  {text: 'Inaktív'},
  {text: 'Hermetikus'},
  {text: 'Fizikai Adeptus'},
  {text: 'Misztikus Adeptus'},
  {text: 'Aligátor Sámán'},
  {text: 'Bagoly Sámán'},
  {text: 'Medve Sámán'},
  {text: 'Bölény Sámán'},
  {text: 'Cápa Sámán'},
  {text: 'Delfin Sámán'},
  {text: 'Egér Sámán'},
  {text: 'Farkas Sámán'},
  {text: 'Holló Sámán'},
  {text: 'Kígyó Sámán'},
  {text: 'Kutya Sámán'},
  {text: 'Macska Sámán'},
  {text: 'Mosómedve Sámán'},
  {text: 'Oroszlán Sámán'},
  {text: 'Patkány Sámán'},
  {text: 'Prérifarkas Sámán'},
  {text: 'Sas Sámán'},
];
