export const skillsUtil: Array<any> = [
  {megjegyzes: 'van', nev: 'Atlétika', csoport: 'Fizikai', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Futás', csoport: 'Fizikai', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Úszás', csoport: 'Fizikai', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Búvárkodás', csoport: 'Fizikai', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Lopakodás', csoport: 'Fizikai', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Akrobatika', csoport: 'Fizikai', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Szabadulás', csoport: 'Fizikai', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Mászás', csoport: 'Fizikai', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Ágyúk', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Dobófegyverek', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Éles fegyverek', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Fegyvertelen harc', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Géppisztolyok', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Lőfegyverek', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Kiberfegyverek', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Korbácsok', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Lézerfegyverek', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Pisztolyok', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Puskák', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Rakétavetők', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Rohampuskák', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Sörétes puskák', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Szálfegyverek', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Tompa fegyverek', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Víz alatti harc', csoport: 'Harci', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Autó', csoport: 'Jármű', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Helikopter', csoport: 'Jármű', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Léghajó', csoport: 'Jármű', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Légpárnás', csoport: 'Jármű', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Motor', csoport: 'Jármű', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Motoros hajó', csoport: 'Jármű', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Nagy hajó', csoport: 'Jármű', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Rakétahajtású', csoport: 'Jármű', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Repülő', csoport: 'Jármű', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Tengeralattjáró', csoport: 'Jármű', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Vitorlás', csoport: 'Jármű', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Auraolvasás', csoport: 'Mágikus', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Szellem Idézés', csoport: 'Mágikus', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Szellem Irányítás', csoport: 'Mágikus', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Szellem Elűzés', csoport: 'Mágikus', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Asztrális projekció', csoport: 'Mágikus', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Varázslás', csoport: 'Mágikus', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Varázsvédelem', csoport: 'Mágikus', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'V. Semlegesítés', csoport: 'Mágikus', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Alkímia', csoport: 'Mágikus', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Csapatvezetés', csoport: 'Szociális', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Etikett', csoport: 'Szociális', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Megfélelmítés', csoport: 'Szociális', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Tanítás', csoport: 'Szociális', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Tárgyalás', csoport: 'Szociális', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Vallatás', csoport: 'Szociális', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Idomítás', csoport: 'Szociális', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Megszemélyesítés', csoport: 'Szociális', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Mesterség', csoport: 'Szociális', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Elrejtés', csoport: 'Szociális', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Navigáció', csoport: 'Szociális', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Érzékelés', csoport: 'Szociális', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Nyomolvasás', csoport: 'Szociális', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Biotechnika', csoport: 'Technikai', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Elektronika', csoport: 'Technikai', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Robbantás', csoport: 'Technikai', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Számítógép', csoport: 'Technikai', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Mechanika', csoport: 'Technikai', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Kémia', csoport: 'Technikai', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Kibertechnológia', csoport: 'Technikai', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Programozás', csoport: 'Technikai', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Érdeklődési körök', csoport: 'Ismeret', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: '6. világbeli ism.', csoport: 'Ismeret', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Háttér ismeretek', csoport: 'Ismeret', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Iskolai ismeretek', csoport: 'Ismeret', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Utcai ismeretek', csoport: 'Ismeret', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Nyelvismeret', csoport: 'Nyelvi', karmaKtsg: 2, kapTul: 'van'},
  {megjegyzes: 'van', nev: 'Írás/olvasás', csoport: 'Nyelvi', karmaKtsg: 2, kapTul: 'van'},
];
